[2024-04-16T14:48:08.405+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T14:48:08.576+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T14:48:08.606+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T14:48:08.608+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T14:48:08.641+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_prep_superstore> on 2024-04-15 00:00:00+00:00
[2024-04-16T14:48:08.665+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T14:48:08.672+0000] {standard_task_runner.py:63} INFO - Started process 260 to run task
[2024-04-16T14:48:08.676+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Superstore_dataprep_kuzmenko', 'data_prep_superstore', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag_by_Kuzmenko.py', '--cfg-path', '/tmp/tmpwp18702l']
[2024-04-16T14:48:08.686+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask data_prep_superstore
[2024-04-16T14:48:09.178+0000] {task_command.py:426} INFO - Running <TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore scheduled__2024-04-15T00:00:00+00:00 [running]> on host b3ab91a725a8
[2024-04-16T14:48:10.184+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='KuzmenkoSV' AIRFLOW_CTX_DAG_ID='Superstore_dataprep_kuzmenko' AIRFLOW_CTX_TASK_ID='data_prep_superstore' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-16T14:48:10.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T14:48:19.651+0000] {logging_mixin.py:188} INFO - [INFO] PostgreSQL connection closed
[2024-04-16T14:48:19.654+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T14:48:19.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T14:48:19.669+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Superstore_dataprep_kuzmenko, task_id=data_prep_superstore, execution_date=20240415T000000, start_date=20240416T144808, end_date=20240416T144819
[2024-04-16T14:48:19.713+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T14:48:19.737+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T14:48:19.743+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
